### ISSUE TITLE
logging error when using mod commands

### ISSUE THREAD

**Issue by AliciaPatty** [The-Aurora-Crew/Quartermaster-Discord-Bot#10]
**Describe the bug**
the inf builder got an issue so it returns the number 4 instead of guild ID

**To Reproduce**
- use any of the mod commands
- check the terminal

**Expected behavior**
the terminal log should tell the guild id and not the number 4

**Additional context**
code where it occurs
https://github.com/The-Aurora-Crew/Quartermaster-Discord-Bot/blob/764167b24db759c1a72b765584bc972d33e539c3/bot/cogs/mod.py#L45

**Comment by NotThatSiri** [comment]
Guess I pushed too quickly. Thanks Alicia for pointing it out

**Comment by AliciaPatty** [comment]
I can fix it and make a pull request
